project:
  type: website

website:
  title: "ISSS608 COURSEWORK"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 0"
          href: "Hands-on Exercises/00.html"
        - text: "Hands-on Exercise 1"
          href: "Hands-on Exercises/Hands-on Ex 01/Hands-on ex 01.html"
        
    right:
    - href: index.qmd
      text: Home
    - "about.qmd"



format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual




