project:
  type: website

website:
  title: "ISSS608 COURSEWORK"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 0"
          href: "Handson_Ex/handson_ex00/Hands-on_Ex00.html"
        
    right:
    - href: index.qmd
      text: Home
    - about.qmd



format:
  html:
    theme: morph
    css: styles.css
    toc: true

editor: visual

