project:
  type: website

website:
  title: "🐢 ISSS608"
  navbar:
    left:
    - text: "Hands-on Exercise"
      menu:
        - text: "Hands-on Exercise 0"
          href: "Hands-on Exercises/00.html"
        - text: "Hands-on Exercise 1"
          href: "Hands-on Exercises/Hands-on Ex 01/Hands-on ex 01.html"
        - text: "Hands-on Exercise 2"
          href: "Hands-on Exercises/Hands-on Ex 02/Hands-on ex 02.html"
        - text: "Hands-on Exercise 3-1"
          href: "Hands-on Exercises/Hands-on Ex 03/Hands-on ex 03.html"
        - text: "Hands-on Exercise 3-2"
          href: "Hands-on Exercises/Hands-on Ex 03/Hands-on ex 3.2.html"
        - text: "Hands-on Exercise 4-1"
          href: "Hands-on Exercises/Hands-on Ex 04/Hands-on ex 4-1.html"
        - text: "Hands-on Exercise 4-2"
          href: "Hands-on Exercises/Hands-on Ex 04/Hands-on ex 4-2.html"
        - text: "Hands-on Exercise 4-3"
          href: "Hands-on Exercises/Hands-on Ex 04/Hands-on ex 4-3.html"
        - text: "Hands-on Exercise 4-4"
          href: "Hands-on Exercises/Hands-on Ex 04/Hands-on ex 4-4.html"
        - text: "Hands-on Exercise 5-1"
          href: "Hands-on Exercises/Hands-on Ex 05/Hands-on ex 5-1.html"
        - text: "Hands-on Exercise 5-2"
          href: "Hands-on Exercises/Hands-on Ex 05/Hands-on ex 5-2.html"
        - text: "Hands-on Exercise 5-3"
          href: "Hands-on Exercises/Hands-on Ex 05/Hands-on ex 5-3.html"
        - text: "Hands-on Exercise 5-4"
          href: "Hands-on Exercises/Hands-on Ex 05/Hands-on ex 5-4.html"
        - text: "Hands-on Exercise 7"
          href: "Hands-on Exercises/Hands-on Ex 07/Hands-on Ex 07.html"
        - text: "Hands-on Exercise 8-1"
          href: "Hands-on Exercises/Hands-on Ex 08/Hands-on Ex 8-1.html"
        - text: "Hands-on Exercise 8-2"
          href: "Hands-on Exercises/Hands-on Ex 08/Hands-on Ex 8-2.html"
        - text: "Hands-on Exercise 8-3"
          href: "Hands-on Exercises/Hands-on Ex 08/Hands-on Ex 8-3.html"
        - text: "Hands-on Exercise 9"
          href: "Hands-on Exercises/Hands-on Ex 09/Hands-on Ex 09.html"
        - text: "Hands-on Exercise 10"
          href: "Hands-on Exercises/Hands-on Ex 10/Hands-on Ex 10.html"
       
      
          
    - text: "In-class Exercise"
      menu:
        - text: "In-class Exercise 1"
          href: "In-class ex/In-class ex04/In-class ex04.html"
        - text: "In-class Exercise 2"
          href: "In-class ex/In-class ex05/In-class ex05.html"
   
    - text: "Take home Exercise"
      menu:
        - text: "Take-home Exercise 1"
          href: "Take home Ex/Take-home_Ex1/Take-home_Ex1.html"
        - text: "Take-home Exercise 2"
          href: "Take home Ex/Take-home_Ex2/Take-home_Ex2.html"
      
          
    
          
    right:
    - href: index.qmd
      text: 🏠
    - href: about.qmd
      text: 🥚



format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual




